### PR TITLE
Add a render-to-texture sample

### PR DESCRIPTION
**Pull request by liaxim**

### CODE REVIEW

**Comment by liaxim** [comment]
Ready for review

**Comment by liaxim** [comment]
Have to redo it to work with https://github.com/Samsung/GearVRf/pull/1099

**Comment by NolaDonato** [comment]
I actually did this already, that is how I tested GVRRenderTarget independently of GVRShadowMap. I will do a pull request for it.

**Comment by NolaDonato** [comment]
Replaced by PR #423 which updpates it to use GVRRenderTarget

**Pull request closed without merging**
