### PR TITLE
gvr-3dcursor: Switch to GVRMain

### PR DESCRIPTION
**Pull request by rahul27**
* Also fixed a few minor bugs

GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by rahul27** [comment]
Depends on https://github.com/Samsung/GearVRf/pull/596

**Comment by rahul27** [comment]
@parthmehta209 could you review and verify?

**Comment by parthmehta209** [comment]
Looks good. I have reviewed and verified.

**Comment by rahul27** [comment]
This one is good to go. Will merge it in later today.

**Pull request merged**
