### PR TITLE
Modified demos with GVRShaderTemplate changes

### PR DESCRIPTION
**Pull request by apjagdale**
Needs https://github.com/Samsung/GearVRf/pull/1201

### CODE REVIEW

**Comment by liaxim** [comment]
This add a gvr-posteffect sample that looks the same as the gvr-blurfilter we already added. Please remove or correct me if I am wrong.

**Comment by NolaDonato** [comment]
Yes the post effect demo is not needed. blur filter does the job.

**Comment by liaxim** [comment]
gvr-accessibility:

1. AccessibilitySceneShader needs to specify GLSL version 100 instead of 300
```
04-27 07:42:46.020 22913 22971 I Adreno  : ERROR: 0:3: 'attribute' : Syntax error:  syntax error
04-27 07:42:46.020 22913 22971 I Adreno  : INTERNAL ERROR: no main() function!
04-27 07:42:46.020 22913 22971 I Adreno  : ERROR: 1 compilation errors.  No code generated.
04-27 07:42:46.020 22913 22971 I Adreno  : 
04-27 07:42:46.020 22913 22971 E gvrf    : Could not compile shader 35633:
04-27 07:42:46.020 22913 22971 E gvrf    : ERROR: 0:3: 'attribute' : Syntax error:  syntax error
04-27 07:42:46.020 22913 22971 E gvrf    : INTERNAL ERROR: no main() function!
04-27 07:42:46.020 22913 22971 E gvrf    : ERROR: 1 compilation errors.  No code generated.
04-27 07:42:46.020 22913 22971 E gvrf    : 
```
2. With 1. fixed the background is missing when you enter the accessibility options scene.

Please double-check all the demos.

**Comment by liaxim** [comment]
gvr-controls: when the pull down menu is activated most of the contents are missing.

The probable cause: for all those texture keys you removed, you have to make sure you set these keys to something in the material (null if you have to) prior to the bindShaders call occurring. Otherwise those textures will never be used.

aa

**Comment by liaxim** [comment]
gvr-vuforia: the teapot is not visible

**Comment by apjagdale** [comment]
Pull request on GearVRf 1201 will fix the gvr-vuforia issue.

**Comment by liaxim** [comment]
Will merge Friday morning.

**Comment by liaxim** [comment]
Btw, gvr-vuforia seems to be crash prone (occasional nullptr dereferences in vuforia code) regardless this change. Anybody else seeing this?

**Pull request merged**
