### PR TITLE
Remove deprecated asset APIs from demos

### PR DESCRIPTION
**Pull request by NolaDonato**
1. gvr-cockpit: use MTL files instead of loadMesh
2. gvr-pickandmove: use GVRSphereSceneObject and GVRCubeSceneObject
instead of OBJ files
3. gvr-sixaxissensor, gvr-modelviewer,  VRBasketBalls: use
GVRAssetLoader.loadMesh instead of GVRContext.loadMesh
4. Fixed build.gradle files of old demos to reference common.gradle with
correct path
This patch depends on pull request #436 from GearVRf-Demos and  #1184 from GearVRF (for the loadMesh call).

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
This bundles in changes from the migration to the shader template pull request. Please keep this change to removing deprecated APIs.

**Comment by NolaDonato** [comment]
Yes I think we should wait on the deprecated asset pull requests until the demos pull request is in. Then I will rebase.

**Comment by liaxim** [comment]
Since https://github.com/Samsung/GearVRf/pull/1184 was closed what should we do about this pull request?

**Comment by NolaDonato** [comment]
I will look at it and figure out if it is redundant.

**Comment by NolaDonato** [comment]
I am closing this pull request and opening a fresh one.

**Pull request closed without merging**
