### PR TITLE
add gvr-rendertotexture

### PR DESCRIPTION
**Pull request by sushantojal**
Adding "gvr-rendertotexture" demo to this branch since it was present in master but not in this branch.
works with openGL.
does not work with vulkan since this demo has lighting.

### CODE REVIEW

**Comment by NolaDonato** [comment]
Edit the demo to not add the light in the Vulkan case so we can test RTT:
if (!GVRShader.isVulkanInstance()) { addLight(...); }

**Comment by sushantojal** [comment]
RTT is not supported on the vulkan branch right now, so this demo will work only with openGL on the vulkan branch.

**Comment by NolaDonato** [comment]
Roshan is fixing this.

**Comment by dnvasilev** [comment]
@NolaDonato : should I merge?

**Pull request merged**
