### PR TITLE
gvr-remote-scripting: updates to the scripts so they work with the latest fw

### PR DESCRIPTION
**Pull request by liaxim**

### CODE REVIEW

**Comment by liaxim** [comment]
If the trex is animated the performance is terrible - ~5 fps on S8. Don't remember it being like that with 3.x. Verified the scripts.

Have not yet tested the various script helpers, namely:
CursorUtils
DisplayUtils
EditorUtils
FileBrowserUtils
PassthroughUtils
SourceUtils

**Comment by NolaDonato** [comment]
We should test the trex animation in the gvr-meshanimation sample to see if it runs OK. That could rule out animation as the issue.

**Comment by liaxim** [comment]
gvr-meshanimation works as expected.

gvr-remote-scripting: few iterations of clearing the scene and pasting the trex script and the framework grinds to a halt. This script is rather simple:

```
importPackage(org.gearvrf);

var scene = gvrf.getMainScene();

var trex_url = new java.net.URL("https://github.com/gearvrf/GearVRf-Demos/raw/master/gvr-meshanimation/app/src/main/assets/TRex_NoGround.fbx");
var trex = gvrf.getAssetLoader().loadModel(trex_url, scene);

trex.getTransform().setPosition(0.0, -10.0, -10.0);
trex.getTransform().setRotationByAxis(90.0, 1.0, 0.0, 0.0);
trex.getTransform().setRotationByAxis(40.0, 0.0, 1.0, 0.0);
trex.getTransform().setScale(1.5, 1.5, 1.5);
trex.setName("trex");
var engine = gvrf.getAnimationEngine();
var animation = trex.getAnimations().get(0);
animation.setRepeatMode(1).setRepeatCount(-1);
animation.start(engine);
```

Will retest the same thing with the maintenance branch.

**Comment by liaxim** [comment]
Ok, looks like some kind of a general scripting problem. Same behavior with the maint branch. One more issue with the scripting.

**Comment by liaxim** [comment]
FileBrowserUtils - shows odd layout
PassthroughUtils - NPEs

It seems to me these have been broken for some time. Might look into them some day.

**Comment by liaxim** [comment]
Planning to merge on Wednesday

**Pull request merged**
