### PR TITLE
Add WidgetLib demo

### PR DESCRIPTION
**Pull request by asg024**
Check corresponding pull requests in GearVRf for widgetLib extension (gvr-widgetlib) and Test repo  (WidgetLibTests)

GearVRf DCO signed off by: Svetlana Gurenkova s.gurenkova@samsung.com

### CODE REVIEW

**Comment by asg024** [comment]
After upgrading to the latest framework, scale animation stopped working in PickerWidget (model picker & background picker) . I will work on this issue separately.

**Comment by asg024** [comment]
Animation has been fixed in latest widgetLib commit

**Comment by liaxim** [comment]
The demo app doesn't always work me. Look like the scale of the models could get messed up. Seems to happen after selecting the "outline" mode.

**Comment by liaxim** [comment]
Sveta is going to address the issues in subsequent PRs. Planning to merge on Friday.

**Pull request merged**
