### PR TITLE
scene editor

### PR DESCRIPTION
**Pull request by parthmehta209**
Adding the scene editor app. 
Depends on https://github.com/Samsung/GearVRf/pull/805 https://github.com/Samsung/GearVRf/pull/804

### CODE REVIEW

**Comment by liaxim** [comment]
I wonder whether the scene editor belongs to the Framework's repo under the tools folder..

**Comment by parthmehta209** [comment]
scene editor needs the scene serializer extension now. May be once we can write to x3d we can put in the framework under the tools.

**Comment by liaxim** [comment]
Needs https://github.com/Samsung/GearVRf/pull/804

**Comment by liaxim** [comment]
Will merge after lunch. The dependency in the framework has been merged.

**Pull request merged**
