### PR TITLE
Modified demos to support the daydream 64 bit backend

### PR DESCRIPTION
**Pull request by rahul27**
GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by rahul27** [comment]
Depends on https://github.com/Samsung/GearVRf/pull/1105

**Comment by thomasflynn** [comment]
question:  do we need to have the 'ARM64' property or do any excluding of .so's now?  seems we can include everything all the time now and let the platform decide which libraries to use.

**Comment by liaxim** [comment]
If android sees any 64bit binary it will assume the app is 64bit. Not always the case but since we are shipping a library not really our responsibility. For the demos build it is useful to have an easy way to force an architecture.

So we could include everything in our aars but we'll have to check the extensions too. Not sure what the deal will be with bullet and especially gdx.

**Comment by liaxim** [comment]
Planning to merge Thursday afternoon.

**Comment by liaxim** [comment]
Will need a rebase

**Comment by rahul27** [comment]
rebased.

**Pull request merged**
