### PR TITLE
fix for outline-sample for vulkan

### PR DESCRIPTION
**Pull request by roshanch**

### CODE REVIEW

**Comment by roshanch** [comment]
I modified gvr-cubemap to remove extra scene-object as compared to master. This sample has gvrStats enabled which uses external textures. To run it on vulkan comment that line.

**Comment by liaxim** [comment]
Shouldn't the stats be handled a bit more gracefully by the vulkan renderer? Like ignoring them automatically.

**Comment by NolaDonato** [comment]
The stats don't work because of an unsupported feature. We can do this:
if (!GVRShader.isVulkanInstance()) { add the stats... }

**Comment by liaxim** [comment]
Should be handled by the framework, not the app, I assume.

**Comment by NolaDonato** [comment]
Actually, we will eventually get these features working in Vulkan and then we will remove all this stuff from the demos.

**Comment by dnvasilev** [comment]
Needs rebase

**Pull request merged**
