### PR TITLE
gvr-3dcursor: Adding support for gearS2

### PR DESCRIPTION
**Pull request by parthmehta209**
Added gearwear as an IoDevice in the app. It can be enabled using
the settings UI or the GearS2Button.

### CODE REVIEW

**Comment by parthmehta209** [comment]
@rahul27 can you review this.

**Comment by rahul27** [comment]
depends on https://github.com/Samsung/GearVRf/pull/592

**Comment by liaxim** [comment]
Needs rebase

**Comment by rahul27** [comment]
Verified.

**Comment by parthmehta209** [comment]
@liaxim I have rebased it now.

**Comment by liaxim** [comment]
@rahul27 Do you think it needs re-verification after the rebase?

**Comment by rahul27** [comment]
Should be fine. You can merge it.

**Pull request merged**
