### PR TITLE
Multilight

### PR DESCRIPTION
**Pull request by NolaDonato**
Multiple lighting sample program

### CODE REVIEW

**Comment by liaxim** [comment]
Looks like DirectLight.java is not needed. It probably should be removed so as not to confuse people.

**Comment by liaxim** [comment]
Looks good to me and works fine.

Got confused a bit because I didn't realize how far the backdrop was away from the model so I didn't quite get the position of the spots. We can address minor things like missing braces later. Nothing that would prevent it from merging.

**Comment by liaxim** [comment]
Can we remove beach.zip, sphere.obj? The jni folder probably can be cleaned up too. Again, something we can do afterwards.

**Comment by liaxim** [comment]
Monoscopic works fine with multiple lights too.

**Comment by NolaDonato** [comment]
I pushed a fix removing these files.

**Pull request merged**
