### PR TITLE
converted applications to android studio

### PR DESCRIPTION
**Pull request by NolaDonato**
Converted the following applications to android studio build (the originals are removed)
collision
complexScene
eye-picking
gamepad 
gvrbulletsample
gvrcamera2renderscript
gvrcockpit_v1_5_0
gvr-cubemap             
gvrjassimpmodelloader   
gvr-litshader           
gvr-multilight          
gvr-meshanimationsample 
simple-gallery          
simple-sample

### CODE REVIEW

**Comment by liaxim** [comment]
Ok, there is a conflict here because of the multilight pull request including Jason's original pull request. Nola and I both have converted some of the samples so I will be cherry-picking from this pull request most likely.

**Comment by liaxim** [comment]
Nola, if you don't mind you may close this pull request. Thanks. All of your commits are in the new pull request.

**Comment by liaxim** [comment]
Nola, I tested gvr-camera2renderscript as you've requested. It doesn't work regardless your conversion. Also it doesn't build in Eclipse post-conversion. I will investigate.

**Comment by liaxim** [comment]
We seem to have missed gvr-cardboard-audio. Will convert it.

**Comment by liaxim** [comment]
Gvr-javascript is another that we might have missed. Will convert.

**Comment by liaxim** [comment]
@jason2kim Could you please let us know what do you want to happen with gvr-video-staticlib-androidstudio? To be removed?

**Comment by jason2kim** [comment]
My suggestion is,
This gvr-video-staticlib-androidstudio is updated from our release URL. But I think it would be helpful to the users if it is maintained here. Of course it now can be renamed: gvr-video-staticlib-androidstudio -> gvr-video-staticlib

gvr-sample-staticlib should be deleted once AS migration is complete.

**Comment by liaxim** [comment]
Status:

- this pull request can be closed
- to my knowledge all samples are converted and support both AS and Eclipse
- gvr-camera2renderscript doesn't work but it didn't prior to the conversation; will be investigated
- will remove gvr-sample-staticlib per Jason
- will rename gvr-video-staticlib-androidstudio and verify it
- will try few samples on a clean Windows machine

**Comment by liaxim** [comment]
Did not get to trying samples on a Windows machine.

**Pull request closed without merging**
