### PR TITLE
Bug fix - Stop the audio in onPause() state.

### PR DESCRIPTION
**Pull request by douglasalipio**
Bug fix - Stop the audio in onPause() state.

### CODE REVIEW

**Comment by thomasflynn** [comment]
needs rebase

**Comment by thomasflynn** [comment]
please rebase.  our VP was complaining about this issue again today.

**Comment by thomasflynn** [comment]
it looks like you've made some commits, but the 'merge pull request' button indicates there are still conflicts and will not let me merge this.

**Comment by thomasflynn** [comment]
still says conflict.

**Comment by douglasalipio** [comment]
I'm checking it.

**Comment by thomasflynn** [comment]
maybe it would be easier to create a new pull request?

**Comment by douglasalipio** [comment]
Yes, this is a good point. I will create a new pull request.

**Pull request closed without merging**
