### PR TITLE
gvr-particles

### PR DESCRIPTION
**Pull request by sushantojal**
Demo showing the usage of APIs exposed by the particle system extension. This has three systems: stars, fireworks and fire+smoke. They can be toggled by tapping.

Depends on https://github.com/Samsung/GearVRf/pull/1277

### CODE REVIEW

**Comment by sushantojal** [comment]
This PR still needs work. Need textures and assets which are our own and have no potential licensing issues.

**Comment by liaxim** [comment]
Please apply the attached diff so we can easily import both the extension and the sample in the framework workspace.
[diff.txt](https://github.com/gearvrf/GearVRf-Demos/files/1184185/diff.txt)

Then you could add this to your extra_settings.gradle (one level below the GearVRf folder):
```
include ':gvr-particles'
project(':gvr-particles').projectDir=new File('../../../GearVRf-Demos/gvr-particles/app')
include ':gvrf-particlesystem'
project(':gvrf-particlesystem').projectDir=new File('../Extensions/gvrf-particlesystem')
```
and have everything in one place to browse and debug.

**Comment by liaxim** [comment]
Can be simply cherry-picked to the vulkan branch. Compiles but produces the same exception as master.

**Comment by sushantojal** [comment]
Should be alright now. Made a change in the demo so that the particle emitter shape should be explicit while creating one.  There are no changes to be made in this demo for it to be used with the vulkan branch.

**Comment by liaxim** [comment]
Looks ok. Planning to merge on Monday.

**Comment by liaxim** [comment]
How about the textures and assets thing?

**Comment by sushantojal** [comment]
GearVRf-DCO-1.0-Signed-off-by: Sushant Ojal
sushant.o@partner.samsung.com

**Comment by sushantojal** [comment]
I had asked Mike to help me out with the textures and assets. Will talk to him again today.

**Comment by sushantojal** [comment]
Added assets made by our team. Should be alright for now. We might be given more assets to make environment look better. Will create a pull request in the future if that happens.

**Pull request merged**
