### PR TITLE
Fix bug in gvr-controller demo with gaze

### PR DESCRIPTION
**Pull request by NolaDonato**
Cursor did not appear when using Gaze controller

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by ragner** [comment]
Hi all,
I can see the cursor now but my Gear controller is not working with this demo anymore 
and I am getting the following fatal exception:

```
 E/AndroidRuntime: FATAL EXCEPTION: GVRGazeEventHandlerThread
                                                                               Process: org.gearvrf.sample.controller, PID: 15202
                                                                               java.lang.NullPointerException: Attempt to write to field 'org.gearvrf.GVRSceneObject org.gearvrf.GVRSceneObject.mParent' on a null object reference
                                                                                   at org.gearvrf.GVRSceneObject.removeChildObject(GVRSceneObject.java:703)
                                                                                   at org.gearvrf.sample.controller.SampleMain$2.stopMove(SampleMain.java:344)
                                                                                   at org.gearvrf.sample.controller.SampleMain$2.onExit(SampleMain.java:399)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
                                                                                   at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:147)
                                                                                   at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
                                                                                   at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
                                                                                   at org.gearvrf.GVRPicker.propagateOnExit(GVRPicker.java:620)
                                                                                   at org.gearvrf.GVRPicker.generatePickEvents(GVRPicker.java:452)
                                                                                   at org.gearvrf.GVRPicker.doPick(GVRPicker.java:400)
                                                                                   at org.gearvrf.GVRPicker.processPick(GVRPicker.java:429)
                                                                                   at org.gearvrf.GVRCursorController.updatePicker(GVRCursorController.java:702)
                                                                                   at org.gearvrf.GVRCursorController.update(GVRCursorController.java:748)
                                                                                   at org.gearvrf.GVRCursorController.setActive(GVRCursorController.java:196)
                                                                                   at org.gearvrf.GVRCursorController.setKeyEvent(GVRCursorController.java:317)
                                                                                   at org.gearvrf.io.GVRGazeCursorController.access$600(GVRGazeCursorController.java:43)
                                                                                   at org.gearvrf.io.GVRGazeCursorController$EventHandlerThread$1.handleMessage(GVRGazeCursorController.java:300)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
10-05 03:33:35.748 15202-15281/org.gearvrf.sample.controller E/libEGL: call to OpenGL ES API with no current context (logged once per thread)

```

**Comment by liaxim** [comment]
@ragner Any specific steps to reproduce? Not reproducing for me yet. I did encounter another exception though.

**Comment by ragner** [comment]
Hi @liaxim,
No, just launch the demo and try use the Gear controller. 

The back button, home and touch touch pad from the Gear controller works well ... 
but it is not possible to move the cursor ... so after some tries I got this fatal exception

**Comment by ragner** [comment]
Hi @liaxim,
I reproduce this issue just once ... :(

**Comment by liaxim** [comment]
@ragner Are you using the very latest framework and demos? There were couple of pull requests merged this morning. Just for reference.

**Comment by ragner** [comment]
I am at:

commit e058fd2f9e0c28ddca15729966ca6c8a4d55501b (HEAD -> maint_v3.x, gvrf/maint_v3.x)
Author: nola.donato@samsung.com <nola.donato@samsung.com>
Date:   Wed Oct 4 14:04:38 2017 -0700

    enable sensor events in gaze controller
    
    This fixes the regression with X3D touch sensors


and


commit e0dafd43e9dd9ca2f7d0238e03c52bb065bebbcd (HEAD -> maint_v3.x, gvrf/maint_v3.x)
Author: Nola Donato <nola.donato@samsung.com>
Date:   Wed Oct 4 23:45:32 2017 -0700

    Fix bug in gvr-controller demo with gaze

**Comment by ragner** [comment]
I am looking for a example of how to use the gear controller with the latest changes ...

**Comment by liaxim** [comment]
gvr-controller would be the best example. Does it work with the gaze controller for you? Just in case, please upload logcat logs. Thans.

**Comment by liaxim** [comment]
By the way, when using the gaze controller the reticle scales as you drag your finger on the screen.

**Comment by ragner** [comment]
@liaxim, Yes.
The demo is always working as GAZE controller.

At onCursorControllerAdded(...) callback I am login the controllers type and it is loging
GAZE only!

**Comment by ragner** [comment]
@liaxim, GAZE controller works well

**Comment by liaxim** [comment]
@ragner So you have a controller but your onCursorControllerAdded callback prints out only gaze available?

**Comment by ragner** [comment]
@liaxim  yes...

but  the back button, home button and touch pad of the controller works!

**Comment by ragner** [comment]
Just the movement of the cursor that does not work

**Comment by ragner** [comment]
@Hi @all,
unfortunately I am still facing this issue ;(

Just gaze controller works for me. I need help with this issue.

**Comment by NolaDonato** [comment]
Do you see the controller model and the red ray?

**Comment by NolaDonato** [comment]
Also check the batteries in your controller. Last night the S8 refused to recognize my controller but when I replaced the batteries it got a lot better.

**Comment by ragner** [comment]
Hi @NolaDonato,
I put a log at onCursorControllerAdded(..)
and I can see only GAZE type ... connected.

But the touch pad, home, and back button of my gear controller works ...

**Comment by ragner** [comment]
The gear controller is working at oculus home.

**Comment by ragner** [comment]
@julianafigueira has checked and
her controller is not working also.

**Comment by ragner** [comment]
My log at GVRInputManager::scanControllers()


10-20 10:51:37.499 3688-3853/org.gearvrf.sample.controller D/XXXX: scanControllers
10-20 10:51:37.499 3688-3853/org.gearvrf.sample.controller D/XXXX: addDevice -1 type GAZE
10-20 10:51:37.507 3688-3853/org.gearvrf.sample.controller D/XXXX: addDevice 1 type UNKNOWN
10-20 10:51:37.508 3688-3853/org.gearvrf.sample.controller D/XXXX: addDevice 2 type GAZE
10-20 10:51:37.508 3688-3853/org.gearvrf.sample.controller D/XXXX: addDevice 3 type GAZE
10-20 10:51:37.509 3688-3853/org.gearvrf.sample.controller D/XXXX: addDevice 4 type GAZE
10-20 10:51:37.509 3688-3853/org.gearvrf.sample.controller D/XXXX: addDevice 5 type GAZE
10-20 10:51:37.510 3688-3853/org.gearvrf.sample.controller D/XXXX: addDevice 6 type UNKNOWN

**Comment by ragner** [comment]
10-20 11:17:08.966 11517-11680/org.gearvrf.sample.controller D/XXXX: scanControllers
10-20 11:17:08.966 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device -1: Virtual
                                                                       Descriptor: a718a782d34bc767f4689c232d64d527998ea7fd
                                                                       Generation: 2
                                                                       Location: built-in
                                                                       Keyboard Type: alphabetic
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x301 ( keyboard dpad )
                                                                      type GAZE
10-20 11:17:08.981 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 1: certify_hall
                                                                       Descriptor: 5a992b125b028d8005f2be21d193b9e73694f332
                                                                       Generation: 14
                                                                       Location: built-in
                                                                       Keyboard Type: none
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x80000000 ( )
                                                                      type UNKNOWN
10-20 11:17:08.981 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 2: Headset
                                                                       Descriptor: e9fbccb20aa36714786b4afad1fe05a9b8b78370
                                                                       Generation: 12
                                                                       Location: built-in
                                                                       Keyboard Type: non-alphabetic
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x101 ( keyboard )
                                                                      type GAZE
10-20 11:17:08.981 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 3: gpio_keys
                                                                       Descriptor: 485d69228e24f5e46da1598745890b214130dbc4
                                                                       Generation: 10
                                                                       Location: built-in
                                                                       Keyboard Type: non-alphabetic
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x101 ( keyboard )
                                                                      type GAZE
10-20 11:17:08.982 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 4: sec_touchpad
                                                                       Descriptor: 6bb78087f323d376bc537679f3f2a4c034fb4659
                                                                       Generation: 58
                                                                       Location: built-in
                                                                       Keyboard Type: non-alphabetic
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x80002103 ( keyboard mouse )
                                                                         AXIS_X: source=0x2002 min=0.0 max=2959.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_Y: source=0x2002 min=0.0 max=1439.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_PRESSURE: source=0x2002 min=0.0 max=1.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_SIZE: source=0x2002 min=0.0 max=1.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOUCH_MAJOR: source=0x2002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOUCH_MINOR: source=0x2002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOOL_MAJOR: source=0x2002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOOL_MINOR: source=0x2002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                      type GAZE
10-20 11:17:08.983 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 5: sec_touchscreen
                                                                       Descriptor: 0fa9d3d0d40f7f5b316320876742e00ad5eb1ba9
                                                                       Generation: 59
                                                                       Location: built-in
                                                                       Keyboard Type: non-alphabetic
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x80001103 ( keyboard touchscreen )
                                                                         AXIS_X: source=0x1002 min=0.0 max=2959.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_Y: source=0x1002 min=0.0 max=1439.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_PRESSURE: source=0x1002 min=0.0 max=1.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_SIZE: source=0x1002 min=0.0 max=1.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOUCH_MAJOR: source=0x1002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOUCH_MINOR: source=0x1002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOOL_MAJOR: source=0x1002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOOL_MINOR: source=0x1002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                      type GAZE
10-20 11:17:08.983 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 6: hall
                                                                       Descriptor: 2786157a00c35a5b99a9677f95108b156b14eb18
                                                                       Generation: 4
                                                                       Location: built-in
                                                                       Keyboard Type: none
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x80000000 ( )
                                                                      type UNKNOWN
10-20 11:17:11.423 11517-11680/org.gearvrf.sample.controller D/XXXX: scanControllers
10-20 11:17:11.423 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device -1: Virtual
                                                                       Descriptor: a718a782d34bc767f4689c232d64d527998ea7fd
                                                                       Generation: 2
                                                                       Location: built-in
                                                                       Keyboard Type: alphabetic
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x301 ( keyboard dpad )
                                                                      type GAZE
10-20 11:17:11.423 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 1: certify_hall
                                                                       Descriptor: 5a992b125b028d8005f2be21d193b9e73694f332
                                                                       Generation: 14
                                                                       Location: built-in
                                                                       Keyboard Type: none
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x80000000 ( )
                                                                      type UNKNOWN
10-20 11:17:11.423 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 2: Headset
                                                                       Descriptor: e9fbccb20aa36714786b4afad1fe05a9b8b78370
                                                                       Generation: 12
                                                                       Location: built-in
                                                                       Keyboard Type: non-alphabetic
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x101 ( keyboard )
                                                                      type GAZE
10-20 11:17:11.423 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 3: gpio_keys
                                                                       Descriptor: 485d69228e24f5e46da1598745890b214130dbc4
                                                                       Generation: 10
                                                                       Location: built-in
                                                                       Keyboard Type: non-alphabetic
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x101 ( keyboard )
                                                                      type GAZE
10-20 11:17:11.423 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 4: sec_touchpad
                                                                       Descriptor: 6bb78087f323d376bc537679f3f2a4c034fb4659
                                                                       Generation: 58
                                                                       Location: built-in
                                                                       Keyboard Type: non-alphabetic
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x80002103 ( keyboard mouse )
                                                                         AXIS_X: source=0x2002 min=0.0 max=2959.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_Y: source=0x2002 min=0.0 max=1439.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_PRESSURE: source=0x2002 min=0.0 max=1.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_SIZE: source=0x2002 min=0.0 max=1.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOUCH_MAJOR: source=0x2002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOUCH_MINOR: source=0x2002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOOL_MAJOR: source=0x2002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOOL_MINOR: source=0x2002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                      type GAZE
10-20 11:17:11.424 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 5: sec_touchscreen
                                                                       Descriptor: 0fa9d3d0d40f7f5b316320876742e00ad5eb1ba9
                                                                       Generation: 59
                                                                       Location: built-in
                                                                       Keyboard Type: non-alphabetic
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x80001103 ( keyboard touchscreen )
                                                                         AXIS_X: source=0x1002 min=0.0 max=2959.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_Y: source=0x1002 min=0.0 max=1439.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_PRESSURE: source=0x1002 min=0.0 max=1.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_SIZE: source=0x1002 min=0.0 max=1.0 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOUCH_MAJOR: source=0x1002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOUCH_MINOR: source=0x1002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOOL_MAJOR: source=0x1002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                         AXIS_TOOL_MINOR: source=0x1002 min=0.0 max=3291.6865 flat=0.0 fuzz=0.0 resolution=0.0
                                                                      type GAZE
10-20 11:17:11.424 11517-11680/org.gearvrf.sample.controller D/XXXX: addDevice Input Device 6: hall
                                                                       Descriptor: 2786157a00c35a5b99a9677f95108b156b14eb18
                                                                       Generation: 4
                                                                       Location: built-in
                                                                       Keyboard Type: none
                                                                       Has Vibrator: false
                                                                       Has mic: false
                                                                       Sources: 0x80000000 ( )
                                                                      type UNKNOWN

**Comment by ragner** [comment]
Hi @NolaDonato,
this patch works to me.

```
GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRInputManager.java
diff --git a/GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRInputManager.java b/GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRInputManager.java
index 17474b47..bd7fc37d 100644
--- a/GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRInputManager.java
+++ b/GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRInputManager.java
@@ -212,9 +212,11 @@ public abstract class GVRInputManager {
         int vendorId = device.getVendorId();
         int productId = device.getProductId();
 
-        if (sources == (InputDevice.SOURCE_TOUCHSCREEN | InputDevice.SOURCE_KEYBOARD)) {
+        if ((sources & InputDevice.SOURCE_TOUCHSCREEN) == InputDevice.SOURCE_TOUCHSCREEN
+                && (sources & InputDevice.SOURCE_KEYBOARD) == InputDevice.SOURCE_KEYBOARD) {
             return GVRControllerType.CONTROLLER;
         }
+
         if ((sources & InputDevice.SOURCE_KEYBOARD) == InputDevice.SOURCE_KEYBOARD ||
             (sources & InputDevice.SOURCE_TOUCHPAD) == InputDevice.SOURCE_TOUCHPAD) {
             // Allow gpio keyboard to be a gaze controller if enabled, also allow                                             
```

**Comment by NolaDonato** [comment]
I tested and didn't find any problems with it. I will include this code in the 4.1 controller reform.

**Comment by ragner** [comment]
Hi @NolaDonato,
I have found one more issue.

If you launch the controller demo with the gear controller connected and than remove
the battery, wait for some seconds e put the battery back .. the picker events of the controller
stops working ...

Also, I would like to have a way of use the GAZE as fallback if the CONTROLLER gets disconnected.

**Pull request merged**
