### PR TITLE
App module name fixes

### PR DESCRIPTION
**Pull request by jason2kim**
Unique application name .apk will be picked from Jenkins script build

GearVRf-DCO-1.0-Signed-off-by: Jason Kim
jason2.kim@samsung.co

### CODE REVIEW

**Comment by thomasflynn** [comment]
needs rebase.

**Comment by jason2kim** [comment]
Will do soon. It requires additional verification from someone as it changes many files.

**Comment by liaxim** [comment]
Alternative way to fix the apk names is by adding this to the module's gradle file:

```
    applicationVariants.all {variant ->
        variant.outputs.each { output ->
            output.outputFile = new File(
                    output.outputFile.parent,
                    rootProject.name + ".apk")
        }
    }
```

The benefit of having this generically named "app" module is that it provides a predictable directory layout. Any automated operations would benefit by not having to discover the sample's module name.

**Comment by jason2kim** [comment]
It seems to be a good solution to me as well

**Comment by jason2kim** [comment]
the new patch: https://github.com/gearvrf/GearVRf-Demos/pull/194

**Pull request closed without merging**
