### PR TITLE
Remove individual demo project files

### PR DESCRIPTION
**Pull request by liaxim**
- impossible to keep them up-to-date
- hopefully forcing everybody to use the top-level project will help with catching build breaks early
- parallel gradle build has been enabled so the performance is pretty good for the top-level project

### CODE REVIEW

**Comment by liaxim** [comment]
Planning to merge on Friday

**Comment by liaxim** [comment]
Since github is unable to show the list of changed files, here it is (``git diff-tree --no-commit-id --name-only -r HEAD``):

```
gvr-360photo/build.gradle
gvr-360photo/gradle.properties
gvr-360photo/gradle/wrapper/gradle-wrapper.jar
gvr-360photo/gradle/wrapper/gradle-wrapper.properties
gvr-360photo/gradlew
gvr-360photo/gradlew.bat
gvr-360photo/settings.gradle
gvr-360video/build.gradle
gvr-360video/gradle.properties
gvr-360video/gradle/wrapper/gradle-wrapper.jar
gvr-360video/gradle/wrapper/gradle-wrapper.properties
gvr-360video/gradlew
gvr-360video/gradlew.bat
gvr-360video/settings.gradle
gvr-3dcursor-simple/build.gradle
gvr-3dcursor-simple/gradle.properties
gvr-3dcursor-simple/gradle/wrapper/gradle-wrapper.jar
gvr-3dcursor-simple/gradle/wrapper/gradle-wrapper.properties
gvr-3dcursor-simple/gradlew
gvr-3dcursor-simple/gradlew.bat
gvr-3dcursor-simple/settings.gradle
gvr-3dcursor/build.gradle
gvr-3dcursor/gradle.properties
gvr-3dcursor/gradle/wrapper/gradle-wrapper.jar
gvr-3dcursor/gradle/wrapper/gradle-wrapper.properties
gvr-3dcursor/gradlew
gvr-3dcursor/gradlew.bat
gvr-3dcursor/settings.gradle
gvr-accessibility/build.gradle
gvr-accessibility/gradle.properties
gvr-accessibility/gradle/wrapper/gradle-wrapper.jar
gvr-accessibility/gradle/wrapper/gradle-wrapper.properties
gvr-accessibility/gradlew
gvr-accessibility/gradlew.bat
gvr-accessibility/settings.gradle
gvr-blurfilter/build.gradle
gvr-blurfilter/gradle.properties
gvr-blurfilter/gradle/wrapper/gradle-wrapper.jar
gvr-blurfilter/gradle/wrapper/gradle-wrapper.properties
gvr-blurfilter/gradlew
gvr-blurfilter/gradlew.bat
gvr-blurfilter/settings.gradle
gvr-bullet/build.gradle
gvr-bullet/gradle.properties
gvr-bullet/gradle/wrapper/gradle-wrapper.jar
gvr-bullet/gradle/wrapper/gradle-wrapper.properties
gvr-bullet/gradlew
gvr-bullet/gradlew.bat
gvr-bullet/settings.gradle
gvr-camera2renderscript/build.gradle
gvr-camera2renderscript/gradle.properties
gvr-camera2renderscript/gradle/wrapper/gradle-wrapper.jar
gvr-camera2renderscript/gradle/wrapper/gradle-wrapper.properties
gvr-camera2renderscript/gradlew
gvr-camera2renderscript/gradlew.bat
gvr-camera2renderscript/settings.gradle
gvr-cardboard-audio/build.gradle
gvr-cardboard-audio/gradle/wrapper/gradle-wrapper.jar
gvr-cardboard-audio/gradle/wrapper/gradle-wrapper.properties
gvr-cardboard-audio/gradlew
gvr-cardboard-audio/gradlew.bat
gvr-cardboard-audio/settings.gradle
gvr-complexscene/build.gradle
gvr-complexscene/gradle.properties
gvr-complexscene/gradle/wrapper/gradle-wrapper.jar
gvr-complexscene/gradle/wrapper/gradle-wrapper.properties
gvr-complexscene/gradlew
gvr-complexscene/gradlew.bat
gvr-complexscene/settings.gradle
gvr-controller/build.gradle
gvr-controller/gradle.properties
gvr-controller/gradle/wrapper/gradle-wrapper.jar
gvr-controller/gradle/wrapper/gradle-wrapper.properties
gvr-controller/gradlew
gvr-controller/gradlew.bat
gvr-controller/settings.gradle
gvr-controls/build.gradle
gvr-controls/gradle.properties
gvr-controls/gradle/wrapper/gradle-wrapper.jar
gvr-controls/gradle/wrapper/gradle-wrapper.properties
gvr-controls/gradlew
gvr-controls/gradlew.bat
gvr-controls/settings.gradle
gvr-cubemap/build.gradle
gvr-cubemap/gradle.properties
gvr-cubemap/gradle/wrapper/gradle-wrapper.jar
gvr-cubemap/gradle/wrapper/gradle-wrapper.properties
gvr-cubemap/gradlew
gvr-cubemap/gradlew.bat
gvr-cubemap/settings.gradle
gvr-events/build.gradle
gvr-events/gradle.properties
gvr-events/gradle/wrapper/gradle-wrapper.jar
gvr-events/gradle/wrapper/gradle-wrapper.properties
gvr-events/gradlew
gvr-events/gradlew.bat
gvr-events/settings.gradle
gvr-eyepicking/build.gradle
gvr-eyepicking/gradle.properties
gvr-eyepicking/gradle/wrapper/gradle-wrapper.jar
gvr-eyepicking/gradle/wrapper/gradle-wrapper.properties
gvr-eyepicking/gradlew
gvr-eyepicking/gradlew.bat
gvr-eyepicking/settings.gradle
gvr-gamepad/build.gradle
gvr-gamepad/gradle.properties
gvr-gamepad/gradle/wrapper/gradle-wrapper.jar
gvr-gamepad/gradle/wrapper/gradle-wrapper.properties
gvr-gamepad/gradlew
gvr-gamepad/gradlew.bat
gvr-gamepad/settings.gradle
gvr-immersivepedia/build.gradle
gvr-immersivepedia/gradle.properties
gvr-immersivepedia/gradle/wrapper/gradle-wrapper.jar
gvr-immersivepedia/gradle/wrapper/gradle-wrapper.properties
gvr-immersivepedia/gradlew
gvr-immersivepedia/gradlew.bat
gvr-immersivepedia/settings.gradle
gvr-javascript/build.gradle
gvr-javascript/gradle/wrapper/gradle-wrapper.jar
gvr-javascript/gradle/wrapper/gradle-wrapper.properties
gvr-javascript/gradlew
gvr-javascript/gradlew.bat
gvr-javascript/settings.gradle
gvr-keyboard/build.gradle
gvr-keyboard/gradle.properties
gvr-keyboard/gradle/wrapper/gradle-wrapper.jar
gvr-keyboard/gradle/wrapper/gradle-wrapper.properties
gvr-keyboard/gradlew
gvr-keyboard/gradlew.bat
gvr-keyboard/settings.gradle
gvr-keyboardview/build.gradle
gvr-keyboardview/gradle.properties
gvr-keyboardview/gradle/wrapper/gradle-wrapper.jar
gvr-keyboardview/gradle/wrapper/gradle-wrapper.properties
gvr-keyboardview/gradlew
gvr-keyboardview/gradlew.bat
gvr-keyboardview/settings.gradle
gvr-lua/build.gradle
gvr-lua/gradle.properties
gvr-lua/gradle/wrapper/gradle-wrapper.jar
gvr-lua/gradle/wrapper/gradle-wrapper.properties
gvr-lua/gradlew
gvr-lua/gradlew.bat
gvr-lua/settings.gradle
gvr-meshanimation/build.gradle
gvr-meshanimation/gradle.properties
gvr-meshanimation/gradle/wrapper/gradle-wrapper.jar
gvr-meshanimation/gradle/wrapper/gradle-wrapper.properties
gvr-meshanimation/gradlew
gvr-meshanimation/gradlew.bat
gvr-meshanimation/settings.gradle
gvr-modelviewer2/build.gradle
gvr-modelviewer2/gradle.properties
gvr-modelviewer2/gradle/wrapper/gradle-wrapper.jar
gvr-modelviewer2/gradle/wrapper/gradle-wrapper.properties
gvr-modelviewer2/gradlew
gvr-modelviewer2/gradlew.bat
gvr-modelviewer2/settings.gradle
gvr-multilight/build.gradle
gvr-multilight/gradle.properties
gvr-multilight/gradle/wrapper/gradle-wrapper.jar
gvr-multilight/gradle/wrapper/gradle-wrapper.properties
gvr-multilight/gradlew
gvr-multilight/gradlew.bat
gvr-multilight/settings.gradle
gvr-outline/build.gradle
gvr-outline/gradle.properties
gvr-outline/gradle/wrapper/gradle-wrapper.jar
gvr-outline/gradle/wrapper/gradle-wrapper.properties
gvr-outline/gradlew
gvr-outline/gradlew.bat
gvr-outline/settings.gradle
gvr-particles/build.gradle
gvr-particles/gradle.properties
gvr-particles/gradle/wrapper/gradle-wrapper.jar
gvr-particles/gradle/wrapper/gradle-wrapper.properties
gvr-particles/gradlew
gvr-particles/gradlew.bat
gvr-particles/settings.gradle
gvr-performance/build.gradle
gvr-performance/gradle.properties
gvr-performance/gradle/wrapper/gradle-wrapper.jar
gvr-performance/gradle/wrapper/gradle-wrapper.properties
gvr-performance/gradlew
gvr-performance/gradlew.bat
gvr-performance/settings.gradle
gvr-polyline/build.gradle
gvr-polyline/gradle.properties
gvr-polyline/gradle/wrapper/gradle-wrapper.jar
gvr-polyline/gradle/wrapper/gradle-wrapper.properties
gvr-polyline/gradlew
gvr-polyline/gradlew.bat
gvr-polyline/settings.gradle
gvr-remote-scripting/build.gradle
gvr-remote-scripting/gradle.properties
gvr-remote-scripting/gradle/wrapper/gradle-wrapper.jar
gvr-remote-scripting/gradle/wrapper/gradle-wrapper.properties
gvr-remote-scripting/gradlew
gvr-remote-scripting/gradlew.bat
gvr-remote-scripting/settings.gradle
gvr-renderableview/build.gradle
gvr-renderableview/gradle.properties
gvr-renderableview/gradle/wrapper/gradle-wrapper.jar
gvr-renderableview/gradle/wrapper/gradle-wrapper.properties
gvr-renderableview/gradlew
gvr-renderableview/gradlew.bat
gvr-renderableview/settings.gradle
gvr-rendertotexture/build.gradle
gvr-rendertotexture/gradle.properties
gvr-rendertotexture/gradle/wrapper/gradle-wrapper.jar
gvr-rendertotexture/gradle/wrapper/gradle-wrapper.properties
gvr-rendertotexture/gradlew
gvr-rendertotexture/gradlew.bat
gvr-rendertotexture/settings.gradle
gvr-sceneobjects/build.gradle
gvr-sceneobjects/gradle.properties
gvr-sceneobjects/gradle/wrapper/gradle-wrapper.jar
gvr-sceneobjects/gradle/wrapper/gradle-wrapper.properties
gvr-sceneobjects/gradlew
gvr-sceneobjects/gradlew.bat
gvr-sceneobjects/scene-objects.iml
gvr-sceneobjects/settings.gradle
gvr-shadows/build.gradle
gvr-shadows/gradle/wrapper/gradle-wrapper.jar
gvr-shadows/gradle/wrapper/gradle-wrapper.properties
gvr-shadows/gradlew
gvr-shadows/gradlew.bat
gvr-shadows/settings.gradle
gvr-simplephysics/build.gradle
gvr-simplephysics/gradle.properties
gvr-simplephysics/gradle/wrapper/gradle-wrapper.jar
gvr-simplephysics/gradle/wrapper/gradle-wrapper.properties
gvr-simplephysics/gradlew
gvr-simplephysics/gradlew.bat
gvr-simplephysics/settings.gradle
gvr-simplesample/build.gradle
gvr-simplesample/gradle.properties
gvr-simplesample/gradle/wrapper/gradle-wrapper.jar
gvr-simplesample/gradle/wrapper/gradle-wrapper.properties
gvr-simplesample/gradlew
gvr-simplesample/gradlew.bat
gvr-simplesample/settings.gradle
gvr-solarsystem/build.gradle
gvr-solarsystem/gradle/wrapper/gradle-wrapper.jar
gvr-solarsystem/gradle/wrapper/gradle-wrapper.properties
gvr-solarsystem/gradlew
gvr-solarsystem/gradlew.bat
gvr-solarsystem/settings.gradle
gvr-solarsystem/solar-system.iml
gvr-switch/build.gradle
gvr-switch/gradle.properties
gvr-switch/gradle/wrapper/gradle-wrapper.jar
gvr-switch/gradle/wrapper/gradle-wrapper.properties
gvr-switch/gradlew
gvr-switch/gradlew.bat
gvr-switch/settings.gradle
gvr-tutorial-lesson2/build.gradle
gvr-tutorial-lesson2/gradle.properties
gvr-tutorial-lesson2/gradle/wrapper/gradle-wrapper.jar
gvr-tutorial-lesson2/gradle/wrapper/gradle-wrapper.properties
gvr-tutorial-lesson2/gradlew
gvr-tutorial-lesson2/gradlew.bat
gvr-tutorial-lesson2/settings.gradle
gvr-tutorial-lesson3/build.gradle
gvr-tutorial-lesson3/gradle.properties
gvr-tutorial-lesson3/gradle/wrapper/gradle-wrapper.jar
gvr-tutorial-lesson3/gradle/wrapper/gradle-wrapper.properties
gvr-tutorial-lesson3/gradlew
gvr-tutorial-lesson3/gradlew.bat
gvr-tutorial-lesson3/settings.gradle
gvr-tutorial-lesson4/build.gradle
gvr-tutorial-lesson4/gradle.properties
gvr-tutorial-lesson4/gradle/wrapper/gradle-wrapper.jar
gvr-tutorial-lesson4/gradle/wrapper/gradle-wrapper.properties
gvr-tutorial-lesson4/gradlew
gvr-tutorial-lesson4/gradlew.bat
gvr-tutorial-lesson4/settings.gradle
gvr-tutorial-lesson5/build.gradle
gvr-tutorial-lesson5/gradle.properties
gvr-tutorial-lesson5/gradle/wrapper/gradle-wrapper.jar
gvr-tutorial-lesson5/gradle/wrapper/gradle-wrapper.properties
gvr-tutorial-lesson5/gradlew
gvr-tutorial-lesson5/gradlew.bat
gvr-tutorial-lesson5/settings.gradle
gvr-tutorial-lesson6/build.gradle
gvr-tutorial-lesson6/gradle.properties
gvr-tutorial-lesson6/gradle/wrapper/gradle-wrapper.jar
gvr-tutorial-lesson6/gradle/wrapper/gradle-wrapper.properties
gvr-tutorial-lesson6/gradlew
gvr-tutorial-lesson6/gradlew.bat
gvr-tutorial-lesson6/settings.gradle
gvr-vuforia/build.gradle
gvr-vuforia/gradle.properties
gvr-vuforia/gradle/wrapper/gradle-wrapper.jar
gvr-vuforia/gradle/wrapper/gradle-wrapper.properties
gvr-vuforia/gradlew
gvr-vuforia/gradlew.bat
gvr-vuforia/gvr-vuforia.iml
gvr-vuforia/settings.gradle
gvr-widgetviewer/build.gradle
gvr-widgetviewer/gradle.properties
gvr-widgetviewer/gradle/wrapper/gradle-wrapper.jar
gvr-widgetviewer/gradle/wrapper/gradle-wrapper.properties
gvr-widgetviewer/gradlew
gvr-widgetviewer/gradlew.bat
gvr-widgetviewer/settings.gradle
gvr-x3d-demo/build.gradle
gvr-x3d-demo/gradle.properties
gvr-x3d-demo/gradle/wrapper/gradle-wrapper.jar
gvr-x3d-demo/gradle/wrapper/gradle-wrapper.properties
gvr-x3d-demo/gradlew
gvr-x3d-demo/gradlew.bat
gvr-x3d-demo/settings.gradle
```

**Comment by thomasflynn** [comment]
shouldn't the automated build be catching build breakages?

**Comment by liaxim** [comment]
It does, but too late - after merging the pull requests and usually we find out the next morning. I can't always build everything first - I assume submitters do but it is not the case every time.

To build and install just a particular demo with the top-level project just run ```./gradlew gvr-whatever:installDebug```. It is as fast as using the individual projects.

**Comment by liaxim** [comment]
@thomasflynn has some concerns not having the individual projects may adversely impact building and using a single app. Like make it much slower. Please try it out and chime in. Maybe we need a different solution.

To build an individual demo app from the top-level project use this: ```./gradlew gvr-whatever:installDebug```. Will postpone merging until there is more feedback. Please provide some.

**Comment by liaxim** [comment]
Will merge on Wednesday

**Pull request merged**
