### PR TITLE
Fixed camera position in x3d-demo and testmodels

### PR DESCRIPTION
**Pull request by NolaDonato**
If the camera is too close to the object, the x3d-demo will reposition it to view the entire model. Also sets the near and far clipping planes from the x3d file.

testmodels scaling was fixed so objects are closer to the camera
GearVRf-DCO-1.0-Signed-off-by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
@NolaDonato There are no changes in this pull requests (Files changed 0).

**Comment by NolaDonato** [comment]
Oops. There are files there now.

**Comment by liaxim** [comment]
My understanding is that Mitch was going to look at the problem this tries to solve. For now not planning to merge this unless I hear updates.

**Comment by mwitchwilliams** [comment]
This code was causing issues.  It was overriding the location of a camera specified in the X3D scene.
We will have some new code likely by September's end that will give X3D more control over the camera and switching camera positions (part of X3D's <Anchor> tag).
Designers may also want a 3d mesh where the camera exists if for example, they want to switch from camera position to camera position, having a 3d mesh marking each camera's location.

**Comment by liaxim** [comment]
Ok then. If there are no objections I will close the pull request tomorrow.

**Pull request closed without merging**
