### PR TITLE
Create tutorials for the new GearVR framework documentation site.

### PR DESCRIPTION
**Pull request by nitosan**
Add sample projects for the new tutorials
1.  a simple gear vr app
2.  a sample app demonstrates how to use Materials
3.  a sample app demonstrates how to use 3d mesh and animation
4.  a sample app demonstrates how to use gaze controller
5.  a sample app demonstrates how to play VR videos

### CODE REVIEW

**Comment by liaxim** [comment]
Will let @NolaDonato chime in.

There is some level of redundancy with the demo apps. Maybe those apps have to become fancier or be removed. Anyway, not something that needs immediate action in my opinion.

**Comment by liaxim** [comment]
@NolaDonato Any comments or we can merge as is?

**Comment by liaxim** [comment]
Planning to merge on Thursday

**Comment by NolaDonato** [comment]
tutorial2_materials: Check lines 56 thru 59. It seems mSphere is assigned to twice.
tutorial3_model_animation: Please avoid using Future<GVRMesh> and Future<GVRTexture>. We will be deprecating these in 4.0. Also you can use import settings with the asset loader to make it put the model in the scene and start the animations for you:
EnumSet<GVRImportSettings> settings = GVRImportSettings.getRecommendedSettingsWith(EnumSet.of(GVRImportSettings.START_ANIMATIONS));
GVRSceneObject character = gvrContext.getAssetLoader().loadModel("astro_boy.dae", settings, true, gvrContext.getMainScene());
To set the repeat count you can do this:
GVRAnimator animator = (GVRAnimator) character.getComponent(GVRAnimator.getComponentType());
animator.setRepeatModel(GVRRepeatMode.REPEATED):
The animator is automatically attached to the model by the asset loader. It also starts the animations for you. But it doesn't know to repeat them or not so you have to set that.
Heads up: I will be changing the controller API slightly so you may need to update the controller sample.

**Pull request merged**
