### PR TITLE
Bullet support

### PR DESCRIPTION
**Pull request by ragner**
Demo to test https://github.com/Samsung/GearVRf/pull/880

GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>
GearVRf-DCO-1.0-Signed-off-by: Frederico Duarte <frederico.sd@samsung.com>
GearVRf-DCO-1.0-Signed-off-by: JulianaFigueira <juliana.f@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Just add ``compile(name:'gvrf-physics-debug', ext:'aar')`` to the dependencies at the end of gvr-bullet/app/build.gradle to have it work with the extension module.

**Comment by NolaDonato** [comment]
When I try to run the example on the Note 4 I get this:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/oculus/systemutils/BuildConfig;

**Comment by liaxim** [comment]
@NolaDonato You probably have VrApi.jar and SystemUtils.jar under the framework libs folder. Check your tree for these two files - they are supposed to be only under the backend_oculus libs folder. Remove other copies and rebuild.

**Comment by NolaDonato** [comment]
That fixed it, thanks

**Comment by NolaDonato** [comment]
I got it to run. Good job. I can't wait until we can apply forces and get collision events. Then we can make a bowling game.

**Comment by ragner** [comment]
Hi @NolaDonato, it is already possible to apply forces. You just need touch the screen to test it. We are aplying a constant  force on the ball.
We are going to finish collision events soon.

**Comment by JulianaFigueira** [comment]
Hi! I just commited a collision event handling example

**Pull request merged**
