### PR TITLE
Bug fix - ImmersivePedia.

### PR DESCRIPTION
**Pull request by douglasalipio**
Bug fix - stop the audio in onPause() state.

### CODE REVIEW

**Comment by douglasalipio** [comment]
@thomasflynn

**Comment by thomasflynn** [comment]
yay, looks mergeable!  Just need to test it now.  Thanks.

**Comment by douglasalipio** [comment]
Sorry for the delay, I am working on another project :(

**Comment by thomasflynn** [comment]
finally had cycles to test it.  works now.  thanks!

**Pull request merged**
