### PR TITLE
Added the Java side source to bullet sample

### PR DESCRIPTION
**Pull request by deepakrawat22**
Its better to debug and there are bugs in Java port which can be fixed with time. Just fixed one bug which I find during hackathon.

GearVRf-DCO-1.0-Signed-off-by: 
Deepak Rawat deepak.rawat@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
@deepakrawat22 There is merge conflict. Please rebase.

**Comment by liaxim** [comment]
Needs a rebase

**Comment by deepakrawat22** [comment]
Rebased to latest

**Comment by liaxim** [comment]
Needs rebase again

**Comment by thomasflynn** [comment]
needs rebase again.

**Comment by deepakrawat22** [comment]
rebased to latest

**Pull request merged**
