### PR TITLE
Adding the 3DCursor sample app

### PR DESCRIPTION
**Pull request by rahul27**
GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by rahul27** [comment]
Depends on https://github.com/Samsung/GearVRf/pull/581. I see some issues using GVRMain.

Will look to move to GVRMain once this pull request goes through.

**Comment by thomasflynn** [comment]
this fails the command line build (which mean it will fail the automated build when that kicks in).  do a ./gradlew assembleDebug
got the following:
Observed package id 'system-images;android-14;default;armeabi-v7a' in inconsistent location '/home/flynnt/trees/android-sdk-linux_x86/system-images/android-14/armeabi-v7a' (Expected '/home/flynnt/trees/android-sdk-linux_x86/system-images/android-14/default/armeabi-v7a')

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module 3DCursorLibrary : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.511 secs

**Comment by rahul27** [comment]
./gradlew assembleDebug worked fine for me, I even tried a build after a clean.

Looks like an issue finding the 3D Cursor Library. Could you confirm that you see it in the GVRf extensions folder? Here is the relative path that has been set in settings.gradle:

../../GearVRf/GVRf/Extensions/3DCursor/3DCursorLibrary

**Comment by thomasflynn** [comment]
yep, sorry, you were right.  I hadn't updated my GearVRf repo.  next (interesting) step with the automated builds will be to hook them up to github for a pre-merge build.  anyway, this can go in.

**Pull request merged**
