### PR TITLE
Added gvr-avatar demo

### PR DESCRIPTION
**Pull request by NolaDonato**
This demo applies animations to an avatar. It is the start of an avatar demo. It depends on PR #1952 from GearVRf

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.,com

### CODE REVIEW

**Comment by liaxim** [comment]
Not all apps compile for me:

```
> Task :gvr-3dcursor-simple:compileDebugJavaWithJavac
/ssd/git/gvrfmaster/GearVRf-Demos/gvr-3dcursor-simple/app/src/main/java/org/gearvrf/io/cursorsimple/CursorMain.java:43: error: cannot find symbol
import org.gearvrf.scene_objects.GVRModelSceneObject;
                                ^
  symbol:   class GVRModelSceneObject
  location: package org.gearvrf.scene_objects
/ssd/git/gvrfmaster/GearVRf-Demos/gvr-3dcursor-simple/app/src/main/java/org/gearvrf/io/cursorsimple/CursorMain.java:85: error: cannot find symbol
        GVRModelSceneObject astronautModel, rocketModel;
        ^
  symbol:   class GVRModelSceneObject
  location: class CursorMain
2 errors

```

**Comment by NolaDonato** [comment]
Oops. I forgot I removed GVRModelSceneObject. We should just use GVRSceneObject. I will go thru the demos and change this.

**Comment by NolaDonato** [comment]
This PR modifies all the demos to compile without GVRModelSceneObject

**Comment by liaxim** [comment]
Merging; otherwise the demos no longer build.

**Pull request merged**
