### PR TITLE
Updated shadow mapping demo

### PR DESCRIPTION
**Pull request by NolaDonato**
To get shadow mapping to work correctly the application needs to set the near and far planes for the shadow map cameras using GVRLightBase.getShadowMaterial. I added this to the application. I did not move any of the objects, but I did change the direction of the spot and direct lights.
1. changed light direction to point at objects to shadow
2. removed commented out code
3. enlarged spotlight cone angle
4. fixed onStep logic to move light horizontally
5. added touch event to start/stop light rotation
6. use asset loader calls instead of deprecated GVRContext versions
7. changed shadow light from aqua to white color
8. remove unused point light

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Needs rebase

**Comment by liaxim** [comment]
Also please revert the renaming of the gvr-modelviewer2/app directory to gvr-modelviewer2/modelviewer2.

**Comment by NolaDonato** [comment]
I reverted the rename -just committing a single file

**Comment by liaxim** [comment]
I still get gvr-modelviewer2/app renamed to gvr-modelviewer2/modelviewer2 with this pull request

**Comment by NolaDonato** [comment]
OK I committed a patch to explicitly rename it

**Comment by liaxim** [comment]
Looks good. Will merge together with https://github.com/Samsung/GearVRf/pull/909

**Pull request merged**
