### PR TITLE
add ExoPlayer lib support

### PR DESCRIPTION
**Pull request by tresvecesseis**
Add ExoPlayer lib for more comprehensive formats support

### CODE REVIEW

**Comment by tresvecesseis** [comment]
to the video demo app

**Comment by thomasflynn** [comment]
Cool!  Thanks for the pull-request.  Looks like a good idea.  @liaxim has some experience with exoplayer and @deepakrawat22 knows the video app the best.  I'll expect they'll review this.   Thanks!

**Comment by tresvecesseis** [comment]
there were some errors rebasing to the current tree, I fixed it but I don´t have the possibility to test the result (no hardware available to test at home), also we are using this with a heavily modified exoplayer lib with multicast IPTV streams so the mediaplayer bits have not been tested as much.

**Comment by deepakrawat22** [comment]
I tested the app, it works fine with exoplayer ON

**Comment by liaxim** [comment]
Looks good. Works fine with both MediaPlayer and ExoPlayer. Thanks.

Will merge in the afternoon.

**Comment by tresvecesseis** [comment]
Thanks for your quick review

**Pull request merged**
